version: "3.8"
services:
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment: 
      - "GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel,grafana-simple-json-datasource,natel-discrete-panel"
    logging:
      options:
        max-size: 20m

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    logging:
      options:
        max-size: 20m

  influx:
    image: influxdb:latest
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - $PWD/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - influx-data:/var/lib/influxdb
      - $PWD/influxdb/scripts:/docker-entrypoint-initdb.d:ro

  unifi-poller:
    image: golift/unifi-poller:latest
    restart: unless-stopped
    environment: 
      - UP_UNIFI_DEFAULT_USER=${UNIFI_USERNAME}
      - UP_UNIFI_DEFAULT_PASS=${UNIFI_PASSWORD}
      - UP_UNIFI_DEFAULT_URL=${UNIFI_URL}
    volumes:
      - $PWD/unifi-poller/unifi-poller.conf:/config/unifi-poller.conf:ro
    logging:
      options:
        max-size: 20m

volumes: 
  grafana-data:
    external: true
  influx-data:
    external: true
